export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_REGISTER = "USER_REGISTER";
export const BOOK_FETCHED = "BOOK_FETCHED";
export const BOOK_CREATED = "BOOK_CREATED";
